he0119/nonebot-plugin-wordcloud

CHANGELOG.md, nonebot_plugin_wordcloud/__init__.py, tests/test_wordcloud.py
=> fix: 修复日期错误时报错的问题

.github/workflows/codecov.yml, .pre-commit-config.yaml
每次加新功能时，都新建一个分支，完成后合并至 master。
=> ci: 删除 dev 分支

nonebot_plugin_wordcloud/__init__.py, nonebot_plugin_wordcloud/config.py, nonebot_plugin_wordcloud/data.py, poetry.lock, pyproject.toml, tests/conftest.py
=> feat: 升级至 nonebot2 b2

CHANGELOG.md, nonebot_plugin_wordcloud/__init__.py, tests/test_wordcloud.py
=> change: 仅当输入词云两个字的时候发送帮助

.github/workflows/release.yml
=> ci: 添加发布的工作流程

CHANGELOG.md, nonebot_plugin_wordcloud/data_source.py, tests/test_pre_process.py
=> fix: 修复网址预处理无法处理掉微博国际版分享地址的问题

CHANGELOG.md, nonebot_plugin_wordcloud/config.py
=> change: 调整 font_path 默认配置设置方法

nonebot_plugin_wordcloud/data_source.py, poetry.lock, pyproject.toml
=> feat: 适配 NoneBot2 RC1

CHANGELOG.md, nonebot_plugin_wordcloud/__init__.py, poetry.lock, tests/test_masked.py
=> fix: 设置/删除词云默认形状的权限调整为仅超级用户

.vscode/launch.json, CHANGELOG.md, nonebot_plugin_wordcloud/data_source.py, nonebot_plugin_wordcloud/utils.py, poetry.lock, pyproject.toml
虽然不知道具体是哪里泄漏了，但是通过每次关闭线程池可以避免这个问题。
fix #99
=> fix: 通过每次关闭线程池修复内存泄漏问题

.github/workflows/codecov.yml, CHANGELOG.md, nonebot_plugin_wordcloud/__init__.py, poetry.lock, tests/test_wordcloud.py
json 中的数据为 base64 编码的字符串，还需要 decode
=> fix: 修复 OneBot 12 协议下下载图片出错的问题

.vscode/launch.json, poetry.lock, pyproject.toml
=> fix: 更新 NoneBug 修复无法测试出错误的问题

CHANGELOG.md, nonebot_plugin_wordcloud/data_source.py, tests/test_colormap.py, tests/test_masked.py, tests/test_wordcloud.py
=> fix: 修复默认词云形状无效的问题

CHANGELOG.md, nonebot_plugin_wordcloud/migrations/f77200370a39_ob12.py
=> fix: 修复运行迁移脚本出错的问题

CHANGELOG.md, README.md, nonebot_plugin_wordcloud/config.py, nonebot_plugin_wordcloud/data_source.py, tests/test_colormap.py
=> feat: 支持直接向词云传递参数

CHANGELOG.md, poetry.lock, pyproject.toml
2.0.1 才有 inherit_supported_adapters 函数。
=> fix: 提高 NoneBot 版本限制修复报错问题

CHANGELOG.md, nonebot_plugin_wordcloud/__init__.py, pyproject.toml
=> feat: 使用 alconna 新提供的依赖注入

nonebot_plugin_wordcloud/migrations/ade8cdca5470_migrate_datastore_data.py
=> fix: 修复迁移出错的问题

tests/conftest.py
=> test: 修复测试中随机的报错

.github/workflows/codecov.yml
```log
zoneinfo._common.ZoneInfoNotFoundError: 
'Multiple conflicting time zone configurations found:
/etc/timezone: Etc/UTC\n/etc/localtime is a symlink to: Asia/Shanghai
Fix the configuration, or set the time zone in a TZ environment variable.
'
```
=> ci: 使用 TZ 环境变量设置时区
